version: "2.1"
services:
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1002
      - PGID=1002
      - MA=Europe/London
    volumes:
      - ${HOME_LOCATION}/heimdall:/config
    ports:
      - 90:80
      - 91:443
    restart: unless-stopped
